#services:
#  postgres:
#    container_name: postgres
#    image: postgres
#    environment:
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: password
#      PGDATA: /data/postgres
#    volumes:
#      - postgres: /data/postgres
#    ports:
#      - "5432:5432"
#    networks:
#      - postgres
#    restart: unless-stopped
#
#  pgadmin:
#    container_name: pgadmin_container
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL:
#      PGADMIN_DEFAULT_PASSWORD:
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#
#    ports:
#      - "5050:80"
#    networks:
#      -postgres
#    restart: unless-stopped
#
#networks:
#  postgres:
#    driver: bridge
#
#volumes:
#  postgres:
#    pgadmin:

#version: '3.1'
#
#services:
#  db:
#    image: postgres
#    restart: always
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: VMP_Demo

#
#  postgres:
#    container_name: postgres_container
#    image: postgres
#    environment:
#      POSTGRES_DB: VMP_Demo
#      POSTGRES_PASSWORD: password
#      PGDATA: /data/postgres
#    volumes:
#      - postgres:/data/postgres
#    ports:
#      - "5432:5432"
#    networks:
#      - postgres
#    restart: unless-stopped
#
#
#  pgadmin:
#    container_name: pgadmin_container
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
#      PGADMIN_DEFAULT_PASSWORD: admin
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    logging:
#      driver: "none"
#
#    ports:
#      - "${PGADMIN_PORT:-5050}:80"
#    networks:
#      - postgres
#    restart: unless-stopped
#
#networks:
#  postgres:
#    driver: bridge
#
#volumes:
#  postgres:
#  pgadmin:


version: '3.7'

services:
  postgres:
      container_name: vm_pg
      image: postgres:9.3.15-alpine
      restart: always
      ports:
        - 5432:5432
      environment:
        - DB_USER=postgres
        - DB_PASS=root


